on: 
  workflow_dispatch:
    inputs:
      ngrok_auth_token:
        description: Your ngrok auth token. login into your ngrok account obtain your token
        required: true
      uptime_seconds:
        type: choice
        description: server will live for this many seconds. max is 6  hours.
        options:
          - "30"
          - "10"
          - "300"
      output_type:
        type: choice
        description: nginx only
        options:
          - nginx

jobs:
  Deploy-nginx-server:
    runs-on: ubuntu-latest
    container:
      image: ubuntu
    steps:
    - run: |
        apt-get update
        apt-get install -y nginx curl
        # Install ngrok
        curl -OLJ https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.tgz
        tar xvzf ngrok-v3-stable-linux-amd64.tgz -C /usr/local/bin
        echo "Server Ready" >> $GITHUB_STEP_SUMMARY
        echo "nginx version: $(nginx -v)" >> $GITHUB_STEP_SUMMARY
        echo "ngrok version: $(ngrok -v)" >> $GITHUB_STEP_SUMMARY
        nginx &
        ps aux | grep nginx
        ss -plunt
        ngrok config add-authtoken ${{ github.event.inputs.ngrok_auth_token }}
        ngrok http 80
        echo "Server up for ${{ github.event.inputs.uptime_seconds }} seconds" >> $GITHUB_STEP_SUMMARY
        sleep ${{ github.event.inputs.uptime_seconds }}
        echo "Bringing Server Down now!" >> $GITHUB_STEP_SUMMARY
        pkill nginx
    - run: |
        echo "Is nginx still installed? $(nginx -v)" >> $GITHUB_STEP_SUMMARY
