on: 
  workflow_dispatch:
    inputs:
      ngrok_auth_token:
        description: "Your ngrok auth token"
        required: false
      uptime_seconds:
        type: choice
        description: server will live for this many seconds. max is 6  hours.
        options:
          - "10"
      output_type:
        type: choice
        description: nginx only
        options:
          - nginx

jobs:
  Deploy-nginx-server:
    runs-on: ubuntu-latest
    container:
      image: ubuntu
    steps:
    - run: |
        apt-get update
        apt-get install -y nginx
        # Install ngrok
        curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | \
        tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null && \
        echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | \
        tee /etc/apt/sources.list.d/ngrok.list && \
        apt update && apt install ngrok
        echo "Server Ready" >> $GITHUB_STEP_SUMMARY
        echo "nginx version: $(nginx -v)" >> $GITHUB_STEP_SUMMARY
        echo "ngrok version: $(ngrok -v)" >> $GITHUB_STEP_SUMMARY
        nginx &
        ps aux | grep nginx
        ss -plunt
        echo "Server up for ${{ github.event.inputs.uptime_seconds }} seconds" >> $GITHUB_STEP_SUMMARY
        sleep ${{ github.event.inputs.uptime_seconds }}
        echo "Bringing Server Down now!" >> $GITHUB_STEP_SUMMARY
        pkill nginx
    - run: |
        echo "Is nginx still installed? $(nginx -v)" >> $GITHUB_STEP_SUMMARY
